import { useCallback, useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/lib/auth';
import { Users, Plus, ArrowLeft, Copy, LockKeyhole } from 'lucide-react';
type Group={id:string;name:string;description:string;alias:string;isOwner:boolean};
type Member={id:string;alias:string;fromMe:boolean;isOwner:boolean};
type Message={id:string;alias:string;content:string;createdAt:string;fromMe:boolean};
export default function GroupsPage(){
 const {getToken,userId}=useAuth();const cache=useQueryClient();const [active,setActive]=useState('');const [name,setName]=useState('');const [description,setDescription]=useState('');const [code,setCode]=useState('');const [invite,setInvite]=useState('');const [text,setText]=useState('');const [notice,setNotice]=useState('');const [error,setError]=useState('');const [before,setBefore]=useState('');
 useEffect(()=>{const fragment=new URLSearchParams(window.location.hash.slice(1));const c=fragment.get('invite');if(c){setCode(c);window.history.replaceState(null,'',window.location.pathname+window.location.search);}},[]);
 const request=useCallback(async<T,>(path:string,method='GET',body?:unknown):Promise<T>=>{const token=await getToken();if(!token)throw Error('Sign in to continue.');const r=await fetch('/api/groups'+path,{method,signal:AbortSignal.timeout(20000),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not complete this action.');return d;},[getToken]);
 const list=useQuery({queryKey:['groups',userId],queryFn:()=>request<{groups:Group[]}>(''),refetchInterval:10000});
 const detail=useQuery({queryKey:['group',userId,active],queryFn:()=>request<{group:Group;members:Member[]}>('/'+active),enabled:!!active,refetchInterval:10000});
 const history=useQuery({queryKey:['group-messages',userId,active,before],queryFn:()=>request<{messages:Message[];hasMore:boolean;nextCursor?:string}>('/'+active+'/messages'+(before?'?before='+encodeURIComponent(before):'')),enabled:!!active,refetchInterval:before?false:3000});
 const refresh=()=>{void cache.invalidateQueries({queryKey:['groups',userId]});void cache.invalidateQueries({queryKey:['group',userId]});void cache.invalidateQueries({queryKey:['group-messages',userId]});};
 const fail=(e:Error)=>{setError(e.message);setNotice('');};
 const create=useMutation({mutationFn:()=>request<{group:Group;inviteCode:string}>('','POST',{name,description}),onSuccess:r=>{setActive(r.group.id);setInvite(r.inviteCode);setName('');setDescription('');setError('');refresh();},onError:fail});
 const join=useMutation({mutationFn:()=>request<{group:Group}>('/join','POST',{code:code.trim()}),onSuccess:r=>{setActive(r.group.id);setInvite('');setCode('');setError('');refresh();},onError:fail});
 const send=useMutation({mutationFn:()=>request('/'+active+'/messages','POST',{content:text.trim()}),onSuccess:()=>{setText('');setBefore('');setError('');refresh();},onError:fail});
 const action=useMutation({mutationFn:({path,method='POST',body}: {path:string;method?:string;body?:unknown})=>request<{inviteCode?:string}>(path,method,body),onSuccess:(r,vars)=>{setError('');if(r.inviteCode)setInvite(r.inviteCode);if(vars.path.endsWith('/leave')||vars.method==='DELETE'){setActive('');setInvite('');setBefore('');}setNotice('Done.');refresh();},onError:fail});
 const open=(id:string)=>{setActive(id);setText('');setInvite('');setBefore('');setNotice('');setError('');};
 const inviteLink=invite?window.location.origin+import.meta.env.BASE_URL.replace(/\/$/,'')+'/groups#invite='+invite:'';
 const copy=async()=>{try{await navigator.clipboard.writeText(inviteLink);setNotice('Invite copied. Anyone with it can join, so share it with people you trust.');}catch{setNotice('Select and copy the invite below.');}};
 const group=detail.data?.group;
 return <main className="mx-auto max-w-5xl px-4 pb-28 pt-8 text-white">
  <p className="text-xs uppercase tracking-widest text-accent">Campus Echo · no GPS</p><h1 className="mt-2 text-4xl font-semibold">Your circles.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Create a group, share an invite, and talk under a nickname. Each group gives you a different alias. Other members do not see your account details.</p>
  {error&&<p role="alert" className="my-4 rounded-xl border border-rose-200/25 p-3 text-rose-200">{error}</p>}{notice&&<p role="status" className="my-4 text-sm text-accent">{notice}</p>}
  {!active?<>
   <div className="my-6 grid gap-4 md:grid-cols-2"><form className="echo-panel" onSubmit={e=>{e.preventDefault();if(!create.isPending)create.mutate();}}><h2 className="flex items-center gap-2 font-semibold"><Plus size={18}/>Create an anonymous group</h2><label className="echo-label">Group name<input className="echo-input" minLength={2} maxLength={60} required value={name} onChange={e=>setName(e.target.value)} placeholder="Late-night conversations"/></label><label className="echo-label">Description<textarea className="echo-input" maxLength={240} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this group for?"/></label><button className="echo-button" disabled={create.isPending}>{create.isPending?'Creating…':'Create group'}</button></form>
   <form className="echo-panel" onSubmit={e=>{e.preventDefault();if(!join.isPending)join.mutate();}}><h2 className="flex items-center gap-2 font-semibold"><LockKeyhole size={18}/>Join with an invite</h2><p className="my-3 text-sm text-white/50">Ask the group owner for a link or code. Groups are visible only to their members.</p><label className="echo-label">Invite code<input className="echo-input font-mono text-sm" required value={code} onChange={e=>{const v=e.target.value.trim();try{setCode(new URLSearchParams(new URL(v).hash.slice(1)).get('invite')||v);}catch{setCode(v);}}} placeholder="Paste invite code or link"/></label><button className="echo-button" disabled={join.isPending}>{join.isPending?'Joining…':'Join group'}</button></form></div>
   <h2 className="mb-4 flex items-center gap-2 text-xl font-semibold"><Users size={20}/>My groups</h2>
   {list.isLoading?<p>Loading groups…</p>:list.isError?<p role="alert">{list.error.message} <button onClick={()=>void list.refetch()}>Retry</button></p>:!list.data?.groups.length?<p className="echo-panel text-white/50">Your first group starts with one invitation.</p>:<div className="grid gap-3 sm:grid-cols-2">{list.data.groups.map(g=><button key={g.id} onClick={()=>open(g.id)} className="echo-panel text-left"><strong className="text-lg">{g.name}</strong><p className="my-2 text-sm text-white/50">{g.description||'A space to talk freely.'}</p><span className="text-xs text-accent">You are {g.alias}{g.isOwner?' · owner':''}</span></button>)}</div>}
  </>:<>
   <button className="mt-5 flex items-center gap-2 text-sm text-accent" onClick={()=>open('')}><ArrowLeft size={16}/>All groups</button>
   {detail.isLoading?<p className="my-6">Opening group…</p>:detail.isError?<div className="echo-panel mt-4" role="alert"><p>{detail.error.message}</p><button onClick={()=>void detail.refetch()}>Retry</button></div>:group&&<>
    <section className="echo-panel my-4"><h2 className="text-2xl font-semibold break-words">{group.name}</h2><p className="mt-2 text-sm text-white/50">{group.description}</p><p className="my-3 text-sm text-accent">You are {group.alias} · {detail.data?.members.length} members</p>
    {group.isOwner?<div className="flex flex-wrap gap-3"><button disabled={action.isPending} className="echo-outline" onClick={()=>{if(window.confirm('Create a new invite? Previous invite links will stop working.'))action.mutate({path:'/'+active+'/invite'});}}>New invite</button><button disabled={action.isPending} className="echo-outline" onClick={()=>{if(window.confirm('Delete this group and all its messages? This cannot be undone.'))action.mutate({path:'/'+active,method:'DELETE'});}}>Delete group</button></div>:<button disabled={action.isPending} className="echo-outline" onClick={()=>{if(window.confirm('Leave this group? You can rejoin using a valid invite.'))action.mutate({path:'/'+active+'/leave'});}}>Leave group</button>}
    {invite&&<div className="mt-4 rounded-xl border border-accent/25 bg-accent/5 p-4"><label className="echo-label">Invite link<input className="echo-input text-xs" readOnly value={inviteLink} onFocus={e=>e.target.select()}/></label><button className="echo-outline inline-flex items-center gap-2" onClick={()=>void copy()}><Copy size={15}/>Copy invite</button><p className="mt-2 text-xs text-white/50">Save this link now. We store a hash of the invite; create a new one if you lose it.</p></div>}
    <details className="mt-4"><summary className="cursor-pointer text-sm text-white/65">Members · nicknames only</summary><ul className="mt-3 space-y-2">{detail.data?.members.map(m=><li key={m.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{m.alias}{m.fromMe?' · you':''}{m.isOwner?' · owner':''}</span>{group.isOwner&&!m.isOwner&&<button disabled={action.isPending} className="text-xs text-rose-200" onClick={()=>{if(window.confirm('Remove this member and prevent them from rejoining?'))action.mutate({path:'/'+active+'/members/'+m.id+'/remove'});}}>Remove</button>}</li>)}</ul></details>
    </section>
    <section className="echo-panel"><h3 className="font-semibold">Group conversation</h3>{history.data?.hasMore&&<button className="echo-outline my-3" onClick={()=>setBefore(history.data?.nextCursor||'')}>Older messages</button>}{before&&<button className="echo-outline my-3 ml-2" onClick={()=>setBefore('')}>Latest messages</button>}
     <div role="log" aria-live="polite" className="my-4 max-h-[480px] space-y-3 overflow-y-auto">{history.isLoading?<p>Loading messages…</p>:history.isError?<p role="alert">{history.error.message} <button onClick={()=>void history.refetch()}>Retry</button></p>:!history.data?.messages.length?<p className="py-8 text-center text-white/40">Say hello. Your alias does the introduction.</p>:history.data.messages.map(m=><article key={m.id} className={`rounded-xl p-3 ${m.fromMe?'bg-primary/15':'bg-white/5'}`}><div className="flex justify-between gap-3 text-xs text-white/50"><span>{m.alias}{m.fromMe?' · you':''}</span><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString()}</time></div><p className="my-2 whitespace-pre-wrap break-words text-sm">{m.content}</p><div className="flex gap-3 text-xs text-white/50">{(m.fromMe||group.isOwner)&&<button disabled={action.isPending} onClick={()=>{if(window.confirm('Delete this message?'))action.mutate({path:'/'+active+'/messages/'+m.id+'/delete'});}}>Delete</button>}{!m.fromMe&&<><button disabled={action.isPending} onClick={()=>{const reason=window.prompt('Why are you reporting this message?');if(reason?.trim())action.mutate({path:'/'+active+'/messages/'+m.id+'/report',body:{reason:reason.trim().slice(0,200)}});}}>Report</button><button disabled={action.isPending} onClick={()=>{if(window.confirm('Hide this participant’s messages from you across Echo?'))action.mutate({path:'/'+active+'/messages/'+m.id+'/block'});}}>Block</button></>}</div></article>)}</div>
     <form onSubmit={e=>{e.preventDefault();if(text.trim()&&!send.isPending)send.mutate();}}><label className="echo-label">Your message<textarea className="echo-input" maxLength={2000} rows={3} value={text} disabled={send.isPending} onChange={e=>setText(e.target.value)} placeholder="Share a thought…"/></label><div className="flex items-center justify-between"><span className="text-xs text-white/40">{text.length}/2000 · text only</span><button className="echo-button" disabled={!text.trim()||send.isPending}>{send.isPending?'Sending…':'Send message'}</button></div></form>
    </section>
   </>}
  </>}
  <details className="mt-6 text-xs leading-6 text-white/45"><summary className="cursor-pointer">How anonymity works</summary><p>Your email and account ID are hidden from members and group owners. Messages are stored by the service and can be reviewed by authorized moderators after reports. This is not end-to-end encryption. Do not share identifying details if you want to remain anonymous. Group messages stay until deleted by their author or owner; public messages expire after 24 hours.</p></details>
 </main>;
}
